apiVersion: dapr.io/v1alpha1
kind: Component
metadata:
  name: reddog.secretstore
  namespace: reddog-retail
spec:
  type: secretstores.local.file
  version: v1
  metadata:
  - name: secretsFile
    value: ./manifests/local/branch/secrets.json